import { Request, Response } from 'express';
import { reportService } from '../../Domain/services/report.service';
import { numberParam } from '../../Api/utils/params';

const id = (req: Request) => Number(req.params.id);
const childId = (req: Request) => Number(req.params.taskId || req.params.blockerId || req.params.achievementId);
export const myList = async (req: Request, res: Response) => res.json({ data: await reportService.listMine(req.userId!, typeof req.query.status === 'string' ? req.query.status : undefined, numberParam(req.query.skip, 0), numberParam(req.query.take, 10, 1, 100), typeof req.query.startDate === 'string' ? req.query.startDate : undefined, typeof req.query.endDate === 'string' ? req.query.endDate : undefined) });
export const all = async (req: Request, res: Response) => res.json({ data: await reportService.listAll(req.query, numberParam(req.query.skip, 0), numberParam(req.query.take, 20, 1, 100)) });
export const getTeamReports = all;
export const getMine = async (req: Request, res: Response) => res.json({ data: await reportService.get(id(req), req.userId!, false) });
export const getManager = async (req: Request, res: Response) => res.json({ data: await reportService.get(id(req), req.userId!, true) });
export const getAccessible = async (req: Request, res: Response) => {
	const manager = req.userRoles?.some((role) => role === 'manager' || role === 'admin') ?? false;
	return res.json({ data: await reportService.get(id(req), req.userId!, manager) });
};
export const create = async (req: Request, res: Response) => res.status(201).json({ data: await reportService.create(req.userId!, req.body) });
export const update = async (req: Request, res: Response) => res.json({ data: await reportService.update(id(req), req.userId!, req.body) });
export const submit = async (req: Request, res: Response) => res.json({ data: await reportService.submit(id(req), req.userId!) });
export const task = async (req: Request, res: Response) => res.status(201).json({ data: await reportService.addTask(id(req), req.userId!, req.body) });
export const updateTask = async (req: Request, res: Response) => res.json({ data: await reportService.updateTask(id(req), childId(req), req.userId!, req.body) });
export const deleteTask = async (req: Request, res: Response) => { await reportService.deleteTask(id(req), childId(req), req.userId!); res.json({ success: true }); };
const resource = (req: Request) => req.path.split('/')[2];
export const child = async (req: Request, res: Response) => res.status(201).json({ data: await reportService.child(resource(req), id(req), req.userId!, req.body) });
export const updateChild = async (req: Request, res: Response) => res.json({ data: await reportService.child(resource(req), id(req), req.userId!, req.body, childId(req)) });
export const deleteChild = async (req: Request, res: Response) => { await reportService.deleteChild(resource(req), id(req), req.userId!, childId(req)); res.json({ success: true }); };
export const time = async (req: Request, res: Response) => res.status(201).json({ data: await reportService.addTime(id(req), req.userId!, req.body) });
export const approve = async (req: Request, res: Response) => res.json({ data: await reportService.review(id(req), req.userId!, 'approved') });
export const requestChanges = async (req: Request, res: Response) => res.json({ data: await reportService.review(id(req), req.userId!, 'needs_correction', req.body.comment) });
export const version = async (req: Request, res: Response) => { const manager = req.userRoles?.some((role) => role === 'manager' || role === 'admin') ?? false; return res.json({ data: await reportService.version(id(req), Number(req.params.versionNumber), req.userId!, manager) }); };
export const versions = async (req: Request, res: Response) => { const manager = req.userRoles?.some((role) => role === 'manager' || role === 'admin') ?? false; return res.json({ data: await reportService.versions(id(req), req.userId!, manager) }); };
export const history = async (req: Request, res: Response) => res.json({ data: await reportService.history(id(req)) });
