import { prisma } from '../../prisma';

const fullInclude = {
  projects: true,
  users_reports_userIdTousers: { select: { id: true, email: true, firstName: true, lastName: true } },
  report_tasks: true,
  report_blockers: true,
  report_achievements: true,
  report_next_week_tasks: true,
  report_time_by_task_type: true,
  report_optional_fields: true,
  report_review_history: { include: { users: { select: { id: true, firstName: true, lastName: true } } }, orderBy: { createdAt: 'desc' as const } },
  report_versions: { include: { report_version_tasks: true }, orderBy: { versionNumber: 'desc' as const } },
} as const;

export const reportRepository = {
  findById: (id: number) => prisma.reports.findUnique({ where: { id }, include: fullInclude }),
  findMine: (userId: number, where: any, skip: number, take: number) => prisma.reports.findMany({ where: { userId, ...where }, skip, take, orderBy: { weekStartDate: 'desc' }, include: { projects: true } }),
  findAll: (where: any, skip: number, take: number) => prisma.reports.findMany({ where: { status: { not: 'draft' }, ...where }, skip, take, orderBy: { weekStartDate: 'desc' }, include: { projects: true, users_reports_userIdTousers: { select: { id: true, firstName: true, lastName: true } } } }),
  count: (where: any) => prisma.reports.count({ where }),
  create: (data: any) => prisma.reports.create({ data, include: fullInclude }),
  update: (id: number, data: any) => prisma.reports.update({ where: { id }, data, include: fullInclude }),
  task: (data: any) => prisma.report_tasks.create({ data }),
  updateTask: (id: number, data: any) => prisma.report_tasks.update({ where: { id }, data }),
  deleteTask: (id: number) => prisma.report_tasks.delete({ where: { id } }),
  blocker: (data: any) => prisma.report_blockers.create({ data }),
  updateBlocker: (id: number, data: any) => prisma.report_blockers.update({ where: { id }, data }),
  deleteBlocker: (id: number) => prisma.report_blockers.delete({ where: { id } }),
  achievement: (data: any) => prisma.report_achievements.create({ data }),
  updateAchievement: (id: number, data: any) => prisma.report_achievements.update({ where: { id }, data }),
  deleteAchievement: (id: number) => prisma.report_achievements.delete({ where: { id } }),
  nextTask: (data: any) => prisma.report_next_week_tasks.create({ data }),
  updateNextTask: (id: number, data: any) => prisma.report_next_week_tasks.update({ where: { id }, data }),
  deleteNextTask: (id: number) => prisma.report_next_week_tasks.delete({ where: { id } }),
  time: (data: any) => prisma.report_time_by_task_type.create({ data }),
  version: (data: any) => prisma.report_versions.create({ data, include: { report_version_tasks: true } }),
  versions: (reportId: number) => prisma.report_versions.findMany({ where: { reportId }, include: { report_version_tasks: true }, orderBy: { versionNumber: 'desc' } }),
  versionByNumber: (reportId: number, versionNumber: number) => prisma.report_versions.findUnique({ where: { reportId_versionNumber: { reportId, versionNumber } }, include: { report_version_tasks: true } }),
  reviewHistory: (reportId: number) => prisma.report_review_history.findMany({ where: { reportId }, include: { users: { select: { id: true, firstName: true, lastName: true } } }, orderBy: { createdAt: 'desc' } }),
  review: (data: any) => prisma.report_review_history.create({ data }),
};
